CREATE TABLE WEB_MEMBER(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID NVARCHAR2(30) NOT NULL,
	USER_PWD NVARCHAR2(30) NOT NULL,
	USER_NAME NVARCHAR2(30) NOT NULL,
	EMAIL NVARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y', 'N'))
); 
SELECT * FROM web_member;
DROP TABLE WEB_MEMBER;

DROP SEQUENCE SEQ_MEMBER_NO;

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

----------------------------

CREATE TABLE WEB_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER REFERENCES WEB_MEMBER,
	BOARD_TITLE NVARCHAR2(50) NOT NULL,
	BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	COUNT NUMBER DEFAULT 0,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y', 'N'))
);

INSERT INTO 
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '첫 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, '두 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '세 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(3, '네 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, '다섯 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, '여섯 번째 글', '안녕하세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, 'ㅁㄴㅇㄻㄴㅇㄻㄴㅇㄻㄴㅇㄹ', '안녕ㅁㄴㅇㄻㄴㅇㄹㅁㄴㅇㄹㅁㄴㄹㅇ세요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(3, 'asdfaasdfaasdfasdfasdf', '안녕asdfasdf하세asdfasdfasdf요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(3, 'dfasdf', 'dfasdfasdf요');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(2, 'asdf', 'ㅇ');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(3, 'a', 'bb');
INSERT INTO
WEB_BOARD(USER_NO, BOARD_TITLE, BOARD_CONTENT)
VALUES(1, 'ㅁㄴㅇㄹ', '마지막');

SELECT 
	   BOARD_NO,
	   BOARD_TITLE,
	   RNUM
  FROM (SELECT 
	   		   BOARD_NO,
	   		   BOARD_TITLE,
	  		   ROWNUM RNUM
  		  FROM (SELECT
	   		   		   BOARD_NO,
	   	   	   		   BOARD_TITLE,
	   	   	   		   ROWNUM
	      		  FROM 
  	   		   		   WEB_BOARD
  	    		 ORDER
		    	 	BY
	   		   		   CREATE_DATE DESC))
 WHERE
	   ROWNUM BETWEEN 1 AND 3;

SELECT 
	   BOARD_NO,
	   BOARD_TITLE
  FROM
  	   WEB_BOARD
 ORDER 
 	BY
 	   CREATE_DATE DESC
OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;

CREATE TABLE WEB_ATTACHMENT(
	FILE_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	REF_BNO NUMBER NOT NULL,
	ORIGIN_NAME VARCHAR2(100) NOT NULL,
	CHANGE_NAME VARCHAR2(50) NOT NULL,
	FILE_PATH VARCHAR2(100) NOT NULL,
	BOARD_TYPE CHAR(1) NOT NULL,
	FILE_LEVEL NUMBER NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT MAX(BOARD_NO) FROM WEB_BOARD;

SELECT
	   BOARD_NO
  FROM (SELECT
  	    	   BOARD_NO
  	      FROM
  	  		   WEB_BOARD
		 ORDER
		 	BY
 	   		   BOARD_NO DESC)
 WHERE 	
       ROWNUM = 1;

CREATE TABLE WEB_NOTICE(
	NOTICE_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NO NUMBER REFERENCES WEB_MEMBER,
	NOTICE_TITLE NVARCHAR2(50) NOT NULL,
	NOTICE_CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	COUNT NUMBER DEFAULT 0,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN ('Y', 'N'))
);

INSERT
  INTO
  	   WEB_NOTICE
  	   (
  	   	USER_NO,
  	   	NOTICE_TITLE, 
  	   	NOTICE_CONTENT
  	   )
VALUES
	   (
	   1, '첫 공지', 'ㅁㄴㅇㄻㄴㅇㄹ'
	   );

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (2, '공지2222222', '공지');

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (3, '공지3333333', '공공지지');

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (1, '공지', '공');

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (3, '공', '지');

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (2, '지', '지');

INSERT INTO WEB_NOTICE(USER_NO, NOTICE_TITLE, NOTICE_CONTENT)
VALUES (1, '돼', '지');


CREATE TABLE WEB_IMAGE_BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE NVARCHAR2(100) NOT NULL,
	BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
	BOARD_WRITER NUMBER REFERENCES WEB_MEMBER,
	CREATE_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_IMAGE NOCACHE;






























